# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 662d90a5b3b515caf0ba6d6dbe9323f45078b1cbaed3ae0e78ddccda1a96f1272036c16a5efc8f4fd36494375dbeea4c92078bde354cd46d1295d6e53ad23f5b

test:
  secret_key_base: c170d20f44982a781430de2ecc186c4d88df272843acf45f45df0c4e49d3d533105d007ec7e75806419fbd2521de058b2486ae1c93329adda2518791cfe143ae

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
